//! Cross-language parity guard: assert `extract_emoji_sequence` reproduces the legacy
//! TypeScript pipeline byte-for-byte over the Unicode emoji-test.txt corpus.
//!
//! `tests/data/emoji_parity_golden.tsv` is the frozen output of the production legacy path
//! (`packages/ingest/src/normalizer.ts`: `text.match(emojiRegex)` then `batchNormalizeEmojis`),
//! regenerated by `tests/data/generate_golden.ts`. Each row is
//! `<input codepoints>\t<emoji1 codepoints>,<emoji2 codepoints>,...` (hex, space-joined within a
//! glyph, comma-joined across glyphs; empty second column = no emoji). A divergence here means the
//! Rust normalizer drifted from the historical TS-produced counts — fix the normalizer, do not
//! silently rebaseline this file.

use emoji_normalizer::extract_emoji_sequence;

const GOLDEN: &str = include_str!("data/emoji_parity_golden.tsv");

fn codepoints_to_string(field: &str) -> String {
    field
        .split(' ')
        .filter(|token| !token.is_empty())
        .map(|hex| {
            let cp = u32::from_str_radix(hex, 16)
                .unwrap_or_else(|_| panic!("invalid codepoint hex {hex:?}"));
            char::from_u32(cp).unwrap_or_else(|| panic!("invalid scalar value {hex:?}"))
        })
        .collect()
}

fn glyph_to_hex(glyph: &str) -> String {
    glyph
        .chars()
        .map(|ch| format!("{:X}", ch as u32))
        .collect::<Vec<_>>()
        .join(" ")
}

#[test]
fn matches_typescript_oracle_golden() {
    let mut total = 0usize;
    let mut diffs: Vec<String> = Vec::new();
    for line in GOLDEN.lines() {
        if line.is_empty() {
            continue;
        }
        let (input_hex, expected) = line
            .split_once('\t')
            .unwrap_or_else(|| panic!("malformed golden row: {line:?}"));
        let input = codepoints_to_string(input_hex);
        let got = extract_emoji_sequence(&input)
            .iter()
            .map(|glyph| glyph_to_hex(glyph))
            .collect::<Vec<_>>()
            .join(",");
        total += 1;
        if got != expected {
            if diffs.len() < 25 {
                diffs.push(format!("  input [{input_hex}]: expected [{expected}], got [{got}]"));
            }
        }
    }
    assert!(total > 5000, "golden corpus unexpectedly small: {total} rows");
    assert!(
        diffs.is_empty(),
        "{} / {total} sequences diverged from the legacy TypeScript oracle:\n{}",
        diffs.len(),
        diffs.join("\n")
    );
}
