/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BackfillRouteImport } from './routes/backfill'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssetsSplatRouteImport } from './routes/assets.$'

const BackfillRoute = BackfillRouteImport.update({
  id: '/backfill',
  path: '/backfill',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsSplatRoute = AssetsSplatRouteImport.update({
  id: '/assets/$',
  path: '/assets/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/backfill': typeof BackfillRoute
  '/assets/$': typeof AssetsSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/backfill': typeof BackfillRoute
  '/assets/$': typeof AssetsSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/backfill': typeof BackfillRoute
  '/assets/$': typeof AssetsSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/backfill' | '/assets/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/backfill' | '/assets/$'
  id: '__root__' | '/' | '/backfill' | '/assets/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BackfillRoute: typeof BackfillRoute
  AssetsSplatRoute: typeof AssetsSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/backfill': {
      id: '/backfill'
      path: '/backfill'
      fullPath: '/backfill'
      preLoaderRoute: typeof BackfillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/$': {
      id: '/assets/$'
      path: '/assets/$'
      fullPath: '/assets/$'
      preLoaderRoute: typeof AssetsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BackfillRoute: BackfillRoute,
  AssetsSplatRoute: AssetsSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
