/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */
import type { ColumnType } from 'kysely';
import type { IPostgresInterval } from 'postgres-interval';

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U> ? ColumnType<S, I | undefined, U> : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Interval = ColumnType<
  IPostgresInterval,
  IPostgresInterval | number | string,
  IPostgresInterval | number | string
>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface _TimescaledbCatalogChunk {
  compressed_chunk_id: number | null;
  creation_time: Timestamp;
  dropped: Generated<boolean>;
  hypertable_id: number;
  id: Generated<number>;
  osm_chunk: Generated<boolean>;
  schema_name: string;
  status: Generated<number>;
  table_name: string;
}

export interface _TimescaledbCatalogChunkColumnStats {
  chunk_id: number;
  column_name: string;
  hypertable_id: number;
  id: Generated<number>;
  range_end: Int8;
  range_start: Int8;
  valid: boolean;
}

export interface _TimescaledbCatalogChunkConstraint {
  chunk_id: number;
  constraint_name: string;
  dimension_slice_id: number | null;
  hypertable_constraint_name: string | null;
}

export interface _TimescaledbCatalogChunkIndex {
  chunk_id: number;
  hypertable_id: number;
  hypertable_index_name: string;
  index_name: string;
}

export interface _TimescaledbCatalogCompressionAlgorithm {
  description: string | null;
  id: number;
  name: string;
  version: number;
}

export interface _TimescaledbCatalogCompressionChunkSize {
  chunk_id: number;
  compressed_chunk_id: number;
  compressed_heap_size: Int8;
  compressed_index_size: Int8;
  compressed_toast_size: Int8;
  numrows_frozen_immediately: Int8 | null;
  numrows_post_compression: Int8 | null;
  numrows_pre_compression: Int8 | null;
  uncompressed_heap_size: Int8;
  uncompressed_index_size: Int8;
  uncompressed_toast_size: Int8;
}

export interface _TimescaledbCatalogCompressionSettings {
  orderby: string[] | null;
  orderby_desc: boolean[] | null;
  orderby_nullsfirst: boolean[] | null;
  relid: string;
  segmentby: string[] | null;
}

export interface _TimescaledbCatalogContinuousAgg {
  direct_view_name: string;
  direct_view_schema: string;
  finalized: Generated<boolean>;
  mat_hypertable_id: number;
  materialized_only: Generated<boolean>;
  parent_mat_hypertable_id: number | null;
  partial_view_name: string;
  partial_view_schema: string;
  raw_hypertable_id: number;
  user_view_name: string;
  user_view_schema: string;
}

export interface _TimescaledbCatalogContinuousAggMigratePlan {
  end_ts: Timestamp | null;
  mat_hypertable_id: number;
  start_ts: Generated<Timestamp>;
  user_view_definition: string | null;
}

export interface _TimescaledbCatalogContinuousAggMigratePlanStep {
  config: Json | null;
  end_ts: Timestamp | null;
  mat_hypertable_id: number;
  start_ts: Timestamp | null;
  status: Generated<string>;
  step_id: Generated<number>;
  type: string;
}

export interface _TimescaledbCatalogContinuousAggsBucketFunction {
  bucket_fixed_width: boolean;
  bucket_func: string;
  bucket_offset: string | null;
  bucket_origin: string | null;
  bucket_timezone: string | null;
  bucket_width: string;
  mat_hypertable_id: number;
}

export interface _TimescaledbCatalogContinuousAggsHypertableInvalidationLog {
  greatest_modified_value: Int8;
  hypertable_id: number;
  lowest_modified_value: Int8;
}

export interface _TimescaledbCatalogContinuousAggsInvalidationThreshold {
  hypertable_id: number;
  watermark: Int8;
}

export interface _TimescaledbCatalogContinuousAggsMaterializationInvalidationLog {
  greatest_modified_value: Int8;
  lowest_modified_value: Int8;
  materialization_id: number | null;
}

export interface _TimescaledbCatalogContinuousAggsWatermark {
  mat_hypertable_id: number;
  watermark: Int8;
}

export interface _TimescaledbCatalogDimension {
  aligned: boolean;
  column_name: string;
  column_type: string;
  compress_interval_length: Int8 | null;
  hypertable_id: number;
  id: Generated<number>;
  integer_now_func: string | null;
  integer_now_func_schema: string | null;
  interval_length: Int8 | null;
  num_slices: number | null;
  partitioning_func: string | null;
  partitioning_func_schema: string | null;
}

export interface _TimescaledbCatalogDimensionSlice {
  dimension_id: number;
  id: Generated<number>;
  range_end: Int8;
  range_start: Int8;
}

export interface _TimescaledbCatalogHypertable {
  associated_schema_name: string;
  associated_table_prefix: string;
  chunk_sizing_func_name: string;
  chunk_sizing_func_schema: string;
  chunk_target_size: Int8;
  compressed_hypertable_id: number | null;
  compression_state: Generated<number>;
  id: Generated<number>;
  num_dimensions: number;
  schema_name: string;
  status: Generated<number>;
  table_name: string;
}

export interface _TimescaledbCatalogMetadata {
  include_in_telemetry: boolean;
  key: string;
  value: string;
}

export interface _TimescaledbCatalogTablespace {
  hypertable_id: number;
  id: Generated<number>;
  tablespace_name: string;
}

export interface _TimescaledbCatalogTelemetryEvent {
  body: Json;
  created: Generated<Timestamp>;
  tag: string;
}

export interface _TimescaledbConfigBgwJob {
  application_name: string;
  check_name: string | null;
  check_schema: string | null;
  config: Json | null;
  fixed_schedule: Generated<boolean>;
  hypertable_id: number | null;
  id: Generated<number>;
  initial_start: Timestamp | null;
  max_retries: number;
  max_runtime: Interval;
  owner: Generated<string>;
  proc_name: string;
  proc_schema: string;
  retry_period: Interval;
  schedule_interval: Interval;
  scheduled: Generated<boolean>;
  timezone: string | null;
}

export interface _TimescaledbInternalBgwJobStat {
  consecutive_crashes: number;
  consecutive_failures: number;
  flags: Generated<number>;
  job_id: number;
  last_finish: Timestamp;
  last_run_success: boolean;
  last_start: Generated<Timestamp>;
  last_successful_finish: Timestamp;
  next_start: Timestamp;
  total_crashes: Int8;
  total_duration: Interval;
  total_duration_failures: Interval;
  total_failures: Int8;
  total_runs: Int8;
  total_successes: Int8;
}

export interface _TimescaledbInternalBgwJobStatHistory {
  data: Json | null;
  execution_finish: Timestamp | null;
  execution_start: Generated<Timestamp>;
  id: Generated<Int8>;
  job_id: number;
  pid: number | null;
  succeeded: Generated<boolean>;
}

export interface _TimescaledbInternalBgwPolicyChunkStats {
  chunk_id: number;
  job_id: number;
  last_time_job_run: Timestamp | null;
  num_times_job_run: number | null;
}

export interface _TimescaledbInternalCompressedChunkStats {
  chunk_name: string | null;
  chunk_schema: string | null;
  compressed_heap_size: Int8 | null;
  compressed_index_size: Int8 | null;
  compressed_toast_size: Int8 | null;
  compressed_total_size: Int8 | null;
  compression_status: string | null;
  hypertable_name: string | null;
  hypertable_schema: string | null;
  uncompressed_heap_size: Int8 | null;
  uncompressed_index_size: Int8 | null;
  uncompressed_toast_size: Int8 | null;
  uncompressed_total_size: Int8 | null;
}

export interface _TimescaledbInternalHypertableChunkLocalSize {
  chunk_id: number | null;
  chunk_name: string | null;
  chunk_schema: string | null;
  compressed_heap_size: Int8 | null;
  compressed_index_size: Int8 | null;
  compressed_toast_size: Int8 | null;
  compressed_total_size: Int8 | null;
  heap_bytes: Int8 | null;
  hypertable_id: number | null;
  hypertable_name: string | null;
  hypertable_schema: string | null;
  index_bytes: Int8 | null;
  toast_bytes: Int8 | null;
  total_bytes: Int8 | null;
}

export interface Posts {
  created_at: Generated<Timestamp>;
  did: string;
  emojis: Generated<string[]>;
  has_emojis: Generated<boolean>;
  langs: Generated<string[]>;
  rkey: string;
  text: string | null;
}

export interface TimescaledbExperimentalPolicies {
  config: Json | null;
  hypertable_name: string | null;
  hypertable_schema: string | null;
  proc_name: string | null;
  proc_schema: string | null;
  relation_name: string | null;
  relation_schema: string | null;
  schedule_interval: Interval | null;
}

export interface TimescaledbInformationChunkCompressionSettings {
  chunk: string | null;
  hypertable: string | null;
  orderby: string | null;
  segmentby: string | null;
}

export interface TimescaledbInformationChunks {
  chunk_creation_time: Timestamp | null;
  chunk_name: string | null;
  chunk_schema: string | null;
  chunk_tablespace: string | null;
  hypertable_name: string | null;
  hypertable_schema: string | null;
  is_compressed: boolean | null;
  primary_dimension: string | null;
  primary_dimension_type: string | null;
  range_end: Timestamp | null;
  range_end_integer: Int8 | null;
  range_start: Timestamp | null;
  range_start_integer: Int8 | null;
}

export interface TimescaledbInformationCompressionSettings {
  attname: string | null;
  hypertable_name: string | null;
  hypertable_schema: string | null;
  orderby_asc: boolean | null;
  orderby_column_index: number | null;
  orderby_nullsfirst: boolean | null;
  segmentby_column_index: number | null;
}

export interface TimescaledbInformationContinuousAggregates {
  compression_enabled: boolean | null;
  finalized: boolean | null;
  hypertable_name: string | null;
  hypertable_schema: string | null;
  materialization_hypertable_name: string | null;
  materialization_hypertable_schema: string | null;
  materialized_only: boolean | null;
  view_definition: string | null;
  view_name: string | null;
  view_owner: string | null;
  view_schema: string | null;
}

export interface TimescaledbInformationDimensions {
  column_name: string | null;
  column_type: string | null;
  dimension_number: Int8 | null;
  dimension_type: string | null;
  hypertable_name: string | null;
  hypertable_schema: string | null;
  integer_interval: Int8 | null;
  integer_now_func: string | null;
  num_partitions: number | null;
  time_interval: Interval | null;
}

export interface TimescaledbInformationHypertableCompressionSettings {
  compress_interval_length: string | null;
  hypertable: string | null;
  orderby: string | null;
  segmentby: string | null;
}

export interface TimescaledbInformationHypertables {
  compression_enabled: boolean | null;
  hypertable_name: string | null;
  hypertable_schema: string | null;
  num_chunks: Int8 | null;
  num_dimensions: number | null;
  owner: string | null;
  tablespaces: string[] | null;
}

export interface TimescaledbInformationJobErrors {
  err_message: string | null;
  finish_time: Timestamp | null;
  job_id: number | null;
  pid: number | null;
  proc_name: string | null;
  proc_schema: string | null;
  sqlerrcode: string | null;
  start_time: Timestamp | null;
}

export interface TimescaledbInformationJobHistory {
  config: Json | null;
  err_message: string | null;
  finish_time: Timestamp | null;
  id: Int8 | null;
  job_id: number | null;
  pid: number | null;
  proc_name: string | null;
  proc_schema: string | null;
  sqlerrcode: string | null;
  start_time: Timestamp | null;
  succeeded: boolean | null;
}

export interface TimescaledbInformationJobs {
  application_name: string | null;
  check_name: string | null;
  check_schema: string | null;
  config: Json | null;
  fixed_schedule: boolean | null;
  hypertable_name: string | null;
  hypertable_schema: string | null;
  initial_start: Timestamp | null;
  job_id: number | null;
  max_retries: number | null;
  max_runtime: Interval | null;
  next_start: Timestamp | null;
  owner: string | null;
  proc_name: string | null;
  proc_schema: string | null;
  retry_period: Interval | null;
  schedule_interval: Interval | null;
  scheduled: boolean | null;
}

export interface TimescaledbInformationJobStats {
  hypertable_name: string | null;
  hypertable_schema: string | null;
  job_id: number | null;
  job_status: string | null;
  last_run_duration: Interval | null;
  last_run_started_at: Timestamp | null;
  last_run_status: string | null;
  last_successful_finish: Timestamp | null;
  next_start: Timestamp | null;
  total_failures: Int8 | null;
  total_runs: Int8 | null;
  total_successes: Int8 | null;
}

export interface DB {
  '_timescaledb_catalog.chunk': _TimescaledbCatalogChunk;
  '_timescaledb_catalog.chunk_column_stats': _TimescaledbCatalogChunkColumnStats;
  '_timescaledb_catalog.chunk_constraint': _TimescaledbCatalogChunkConstraint;
  '_timescaledb_catalog.chunk_index': _TimescaledbCatalogChunkIndex;
  '_timescaledb_catalog.compression_algorithm': _TimescaledbCatalogCompressionAlgorithm;
  '_timescaledb_catalog.compression_chunk_size': _TimescaledbCatalogCompressionChunkSize;
  '_timescaledb_catalog.compression_settings': _TimescaledbCatalogCompressionSettings;
  '_timescaledb_catalog.continuous_agg': _TimescaledbCatalogContinuousAgg;
  '_timescaledb_catalog.continuous_agg_migrate_plan': _TimescaledbCatalogContinuousAggMigratePlan;
  '_timescaledb_catalog.continuous_agg_migrate_plan_step': _TimescaledbCatalogContinuousAggMigratePlanStep;
  '_timescaledb_catalog.continuous_aggs_bucket_function': _TimescaledbCatalogContinuousAggsBucketFunction;
  '_timescaledb_catalog.continuous_aggs_hypertable_invalidation_log': _TimescaledbCatalogContinuousAggsHypertableInvalidationLog;
  '_timescaledb_catalog.continuous_aggs_invalidation_threshold': _TimescaledbCatalogContinuousAggsInvalidationThreshold;
  '_timescaledb_catalog.continuous_aggs_materialization_invalidation_log': _TimescaledbCatalogContinuousAggsMaterializationInvalidationLog;
  '_timescaledb_catalog.continuous_aggs_watermark': _TimescaledbCatalogContinuousAggsWatermark;
  '_timescaledb_catalog.dimension': _TimescaledbCatalogDimension;
  '_timescaledb_catalog.dimension_slice': _TimescaledbCatalogDimensionSlice;
  '_timescaledb_catalog.hypertable': _TimescaledbCatalogHypertable;
  '_timescaledb_catalog.metadata': _TimescaledbCatalogMetadata;
  '_timescaledb_catalog.tablespace': _TimescaledbCatalogTablespace;
  '_timescaledb_catalog.telemetry_event': _TimescaledbCatalogTelemetryEvent;
  '_timescaledb_config.bgw_job': _TimescaledbConfigBgwJob;
  '_timescaledb_internal.bgw_job_stat': _TimescaledbInternalBgwJobStat;
  '_timescaledb_internal.bgw_job_stat_history': _TimescaledbInternalBgwJobStatHistory;
  '_timescaledb_internal.bgw_policy_chunk_stats': _TimescaledbInternalBgwPolicyChunkStats;
  '_timescaledb_internal.compressed_chunk_stats': _TimescaledbInternalCompressedChunkStats;
  '_timescaledb_internal.hypertable_chunk_local_size': _TimescaledbInternalHypertableChunkLocalSize;
  posts: Posts;
  'timescaledb_experimental.policies': TimescaledbExperimentalPolicies;
  'timescaledb_information.chunk_compression_settings': TimescaledbInformationChunkCompressionSettings;
  'timescaledb_information.chunks': TimescaledbInformationChunks;
  'timescaledb_information.compression_settings': TimescaledbInformationCompressionSettings;
  'timescaledb_information.continuous_aggregates': TimescaledbInformationContinuousAggregates;
  'timescaledb_information.dimensions': TimescaledbInformationDimensions;
  'timescaledb_information.hypertable_compression_settings': TimescaledbInformationHypertableCompressionSettings;
  'timescaledb_information.hypertables': TimescaledbInformationHypertables;
  'timescaledb_information.job_errors': TimescaledbInformationJobErrors;
  'timescaledb_information.job_history': TimescaledbInformationJobHistory;
  'timescaledb_information.job_stats': TimescaledbInformationJobStats;
  'timescaledb_information.jobs': TimescaledbInformationJobs;
}
