/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string>;

export interface Emojis {
  created_at: Generated<Timestamp>;
  emoji: string;
  id: Generated<number>;
  lang: string;
  post_id: number;
}

export interface EmojiStats {
  count: Generated<number>;
  created_at: Generated<Timestamp>;
  emoji: string;
  lang: string;
}

export interface Posts {
  cid: string;
  created_at: Generated<Timestamp>;
  did: string;
  has_emojis: Generated<boolean>;
  id: Generated<number>;
  langs: Generated<string[]>;
  rkey: string;
}

export interface DB {
  emoji_stats: EmojiStats;
  emojis: Emojis;
  posts: Posts;
}
